[package]
name = "donburako"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
uuid.workspace = true
thiserror.workspace = true
tokio = { workspace = true }
tokio-util.workspace = true
log.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt"] }
